### ISSUE TITLE
Android Overlay useNavigationComponentDidAppear not working on release

### ISSUE THREAD

**Issue by rendomnet** [underscopeio/react-native-navigation-hooks#1]
On Android useNavigationComponentDidAppear not working when used in overlay in release.
When debugging it is working.

"react-native-navigation-hooks": "^2.21.0",
"react-native-navigation": "^2.22.1",

**Comment by rendomnet** [comment]
will close issue till more info

**Comment by jpgarcia** [comment]
Hi @rendomnet could you confirm that this is an issue with this library and not a `react-native-navigation` issue? 

You can try doing this in your component to check if the listener is actually working:
```js
Navigation.events().registerComponentDidAppearListener(event => {
    alert(event.componentId)
})
```

In any case, it would be great if you can provide us a public repo so we can reproduce the issue.

**Comment by rendomnet** [comment]
@jpgarcia I have converted my overlay back to **Component** from functional component. And componentDidAppear works.

**Comment by jpgarcia** [comment]
@rendomnet ok, I will close this issue for now. 
BTW I'm trying to reproduce the issue. I'll keep you posted on any finding.
thanks!

**Comment by jpgarcia** [comment]
@rendomnet I can confirm that I could reproduce the issue and I found that it happens if you use `showModal` or `push` also. 

I'll create a new issue on `react-native-navigation` with as it's not related to this library

Thank you for reporting this!

**Comment by jpgarcia** [comment]
@rendomnet I've just reported the issue on RNN project if you wanna take a look https://github.com/wix/react-native-navigation/issues/5244
