### ISSUE TITLE
useNavigationComponentDidAppear not appear 

### ISSUE THREAD

**Issue by loga4** [underscopeio/react-native-navigation-hooks#22]
some strange bug, i'm not sure that it's a that package bug, but:

working:
```js
const Func = ({ componentId}) => {
  useNavigationComponentDidAppear(() => {
    console.log('test')
  }, componentId);

  let { key1, key2 } = useSelector((state) => ({
    key1: state.key1,
    key2: state.key2,
  }), shallowEqual)
}
```

working
```js
const Func = ({ componentId}) => {
  useNavigationComponentDidAppear(() => {
    console.log('test')
  }, componentId);

  let { key1, key2 } = useSelector((state) => state.key1)
}
```

NOT working (without shallowEqual from react-redux):
```javascript
const Func = ({ componentId}) => {
  useNavigationComponentDidAppear(() => {
    console.log('test')
  }, componentId);

  let { key1, key2 } = useSelector((state) => ({
    key1: state.key1,
    key2: state.key2,
  }))
}
```

**Comment by jpgarcia** [comment]
Hi @loga4 thank you for reporting this. I'm not getting what the issue. Is about Is the console.log never executed in the third example?

Could you please give us more details like versions of RN/RNN/..., repro steps or even better a minimal public Github repo so we can troubleshoot the issue?

**Comment by loga4** [comment]
I can’t reproduce this issue on the project from scratch(0.62), but it’s easy to reproduce on my current project) I’ll try to build a small project)

react 16.13.1
react-native 0.61.5
react-native-navigation 6.4.0
react-native-navigation-hooks 5.0.0

**Comment by jpgarcia** [comment]
Ok, meanwhile I'll closed this as the issue you're facing doesn't seem to be related with this library. Feel free to reopen it once you can provide a detailed scenario and clear repro steps.
