### ISSUE TITLE
Command: cd example && yarn install failed

### ISSUE THREAD

**Issue by sertaconay** [underscopeio/react-native-navigation-hooks#30]
Hello. (:

I've already installed 6.0.0 but when I try to upgrade it to 6.0.1 and I get the output below:

```
[4/6] ⠄ react-native-navigation-hooks
error /xxx/node_modules/react-native-navigation-hooks: Command failed.
Exit code: 1
Command: cd example && yarn install
Arguments: 
Directory: /xxx/node_modules/react-native-navigation-hooks
Output:
```

> macOS Catalina 10.15.4
➜ node -v && yarn -v   
v12.16.2
1.22.4

**Comment by aschenkel** [comment]
@sertaconay thanks! `v6.0.2` should be out soon with the fix
