### ISSUE TITLE
useNavigationComponentDidAppear handler get fired when componentId is undefined

### ISSUE THREAD

**Issue by samithaf** [underscopeio/react-native-navigation-hooks#35]
First of all thank you for the awesome little library. I just noticed that useNavigationComponentDidAppear handler get attached when the componentId becomes undefined which leads to a potential memory leak since React can't destroy the component properly.

How to reproduce: (As you can see I have change prop name from componentId to componentID). This is an edge case since in TS config componentId marked as optional and the way I found the issue was someone in my team accidentally used following hook in a non-react native navigation registered screen which leads to componentId to become undefined.  

```
const [ready, setReady] = useState();
useNavigationComponentDidAppear(async () => {
    setReady(true)
  }, props.componentID);
```

**Comment by eduardopelitti** [comment]
Hi @samithaf,

First of all, thank you for taking the time to report this issue!

Your report has led to some internal discussion within the team on how to handle this case and similar ones, so we will be looking into it.

I'll keep the issue updated with new info when something comes up.

**Comment by jpgarcia** [comment]
Hi @samithaf based on your suggestion we've updated the library to log warning messages if you don't provide a `componentId` as you suggested.

You can find more info about the **6.1.0** updates here https://underscopeio.github.io/react-native-navigation-hooks/docs/migration-guide

Thanks for reporting this one!
