### ISSUE TITLE
dismissOverlay doesn't work

### ISSUE THREAD

**Issue by kakakalot** [underscopeio/react-native-navigation-hooks#39]
System:
```
react-native: 0.62.2
react-native-navigation: 6.11
react-native-navigation-hooks: 6.1
```

Description:
- As the title,  we call `dismissOverlay` function, it doesn't work.
- I think the reason is it has no input param as the original one
https://wix.github.io/react-native-navigation/api/overlay#dismissoverlay

**Comment by jpgarcia** [comment]
Hi @kakakalot thanks for reporting this. could you please check that you're providing a context for the `useNavigation` hook or passing the componentId as parameter?

### Using context 
```tsx
const MyScreen = () => {
  const { dismissOverlay } = useNavigation() // << Assumes you're providing a NavigationContext
}
```
You can find more info on how to setup the context here: 
- https://underscopeio.github.io/react-native-navigation-hooks/docs/before-you-start#the-navigationcontext
- https://underscopeio.github.io/react-native-navigation-hooks/docs/contexts 
- https://underscopeio.github.io/react-native-navigation-hooks/docs/hocs

### Without context 
```tsx
const MyScreen = ({ componentId }) => {
  const { dismissOverlay } = useNavigation(componentId)
}
```

**Comment by jpgarcia** [comment]
@kakakalot I tested this locally and seems to be working as expected

I'm closing this for now. Feel free to reopen if you couldn't get it working!

**Comment by kakakalot** [comment]
@jpgarcia 
```
export const useLoadingScreen = () => {
  const {showOverlay, dismissOverlay} = useNavigation();
  const show = () =>
    showOverlay({
      component: {id: 'Loading', name: 'Loading'},
    });
  const dismiss = () => dismissOverlay();

  return {show, dismiss};
};
```

Above is my custom hook. The `show` function is ok, but the `dismiss` is not.
And this is `registerComponents` function with using `NavigationProvider`
```
import {Navigation} from 'react-native-navigation';
import {NavigationProvider} from 'react-native-navigation-hooks';
import React from 'react';

type ComponentScreenType = {
  [key: string]: React.ComponentType;
};
const ComponentScreens: ComponentScreenType = {
  Loading,
  LoanList,
  SubmitLoan,
  RepayLoan,
  LoanDetail,
};

export const registerComponents = () => {
  Object.keys(ComponentScreens).forEach((name) => {
    const ComponentScreen = ComponentScreens[name];

    Navigation.registerComponent(
      name,
      () => (props) => {
        return (
          <NavigationProvider value={{componentId: props.componentId}}>
            <StoreContext.Provider value={stores}>
              <ComponentScreen {...props} />
            </StoreContext.Provider>
          </NavigationProvider>
        );
      },
      () => ComponentScreen,
    );
  });
};
```

**Comment by jpgarcia** [comment]
Since you're passing an `id` to the show overlay I think what you're missing here is passing the `id` to the `dismissModal` function:

```tsx
const LOADING_ID = 'Loading';

export const useLoadingScreen = () => {
  const {showOverlay, dismissOverlay} = useNavigation();
  const show = () =>
    showOverlay({
      component: {id: LOADING_ID, name: 'Loading'},
    });
  const dismiss = () => dismissOverlay(LOADING_ID);

  return {show, dismiss};
};
```

Let me know if it helps!

**Comment by kakakalot** [comment]
@jpgarcia 
As my first comment, the `dismissOverlay ` hook function doesn't have input param. How can I pass the `id`?
You can see [here](https://github.com/underscopeio/react-native-navigation-hooks/blob/bda383ec1425311f7c246b37f3290c2ed1cb30bc/src/helpers/createNavigationCommands.ts#L44)

**Comment by jpgarcia** [comment]
You're right my mistake!

The `useNavigation` gets the `componentId` from the context or using args `useNavigation(componentId)` then internally it call the [createNavigationCommands](https://github.com/underscopeio/react-native-navigation-hooks/blob/master/src/helpers/createNavigationCommands.ts#L59) factory which provides the `componentId` to the `dismissOverlay` function.

Being said that I think in your case you should either invoke `const {showOverlay, dismissOverlay} = useNavigation(LOADING_ID);` or use the `Navigation.dismissModal` right away from RNN.

Make sense?

**Comment by kakakalot** [comment]
@jpgarcia 
`dismissOverlay` still didn't work after i had tried
```const {showOverlay, dismissOverlay} = useNavigation(LOADING_ID);```

the loading screen was showed by `showOverlay` function, but it could not be dismissed by `dismissOverlay`

**Comment by jpgarcia** [comment]
Hi @kakakalot I've just submitted a new version of the lib that should work using `useNavigation(componentId)` as I mentioned before

Thank you for reporting this!

**Comment by kakakalot** [comment]
@jpgarcia 
Thank for your work. I already upgraded react-native-navigation-hooks to v6.1.1 but It throws error when `dismissOverlay` function is called

```ts
[Sun Sep 13 2020 22:49:52.642]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: ComponentId not found
promiseMethodWrapper@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3718:45
dismissOverlay@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:100022:62
dismiss@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:111951:28
```

I used `useNavigation` in my custom hook function as below:
```tsx
export const useLoadingScreen = () => {
  const {showOverlay, dismissOverlay} = useNavigation('Loading_ID');
  const show = () =>
    showOverlay({
      component: {name: 'Loading'},
    });
  const dismiss = () => dismissOverlay();

  return {show, dismiss};
};

const Loading = () => (
  <View style={styles.container}>
    <ActivityIndicator size="large" color="white" />
  </View>
);

export default Loading;
```

**Comment by jpgarcia** [comment]
Hi @kakakalot I think you're missing to pass the `componentId` to the `showOverlay` function

```ts
export const useLoadingScreen = () => {
  const {showOverlay, dismissOverlay} = useNavigation('Loading_ID');
  const show = () =>
    showOverlay({
      component: {id: 'Loading_ID', name: 'Loading'},
    });
  const dismiss = () => dismissOverlay();

  return {show, dismiss};
};
```

**Comment by kakakalot** [comment]
it works. Thank you
