### ISSUE TITLE
Compatibility with RNN version 7

### ISSUE THREAD

**Issue by tiagomelilo** [underscopeio/react-native-navigation-hooks#42]
I upgraded the RNN version to 7.1.0, but I noticed some errors, as attached.

Will it be necessary to adapt this library to work with RNN v7?
<img width="323" alt="Captura_de_Tela_2020-10-06_as_17 41 33" src="https://user-images.githubusercontent.com/6058314/95352423-9b63eb00-0898-11eb-913b-55a4d04f986e.png">

**Comment by ignacioola** [comment]
Hi @tiagomelilo, I wasn't able to reproduce the issue with a clean react native project. Could you provide more info from your context? Also, some repro-steps would be nice.

Thanks!
