### ISSUE TITLE
[Question] Is RRN v7 supported?

### ISSUE THREAD

**Issue by nelsonprsousa** [underscopeio/react-native-navigation-hooks#50]
Hi friends,

Based on [docs](https://underscopeio.github.io/react-native-navigation-hooks/docs/installing#supported-versions), these are the current supported versions:
<table>
  <tr>
    <td>RN Navigation</td>
    <td align="center">&gt;= 2.21.0</td>
    <td align="center">&gt;= 4.0.7</td>
    <td align="center">&gt;= 4.5.0</td>
    <td align="center">&gt;= 6.5.0</td>
  </tr>
  <tr>
    <td>RN Navigation Hooks</td>
    <td align="center">&lt;= 3.x.x</td>
    <td align="center"> 4.x.x</td>
    <td align="center"> 5.x.x</td>
    <td align="center"> 6.x.x</td>
  </tr>
</table>

However RNN is already in 7.x.x. Can we still use this library?

Thank you

**Comment by jpgarcia** [comment]
You can use 7.x.x ! we're actually using it in some projects with RNN latest version!

I'll update the docs based on your feedback thanks!
