### ISSUE TITLE
useNavigationComponentDidAppear randomly not works on Android

### ISSUE THREAD

**Issue by sintylapse** [underscopeio/react-native-navigation-hooks#7]
On android `useNavigationComponentDidAppear` some times not works, probably because `useEffect` creates subscription after mount, but in RNN you usually do `Navigation.events().bindComponent(this)` inside constructor, not inside `componentDidMount`.

If in your code you replace `useEffect` with any other hook, that is triggered without waiting for mount, it will work fine. `useLayoutEffect` fits perfectly here because it have the same signature as `useEffect`, but it runs before render. Also everything works fine after replacing functional component with class component.

Maybe it is reasonable to replace `useEffect` with `useLayoutEffect`?

**Comment by jpgarcia** [comment]
Wow! this is awesome, good catch dude! I just tried your suggestion and it works like a charm!

I'll create PR and publish a new version ASAP

Thank you!

**Comment by jpgarcia** [comment]
Closing this in favor of #8 Just published [v3.2.0](https://github.com/underscopeio/react-native-navigation-hooks/releases/tag/v3.2.0) 🎉

**Comment by sintylapse** [comment]
@jpgarcia Thank you for responding to this so quick!
